import type { Config } from 'tailwindcss'

// Inlined from src/styles/design-system.config.ts to resolve build import errors
const designSystem = {
  colors: {
    primary: {
      50: '#eff6ff',
      100: '#dbeafe',
      200: '#bfdbfe',
      300: '#93c5fd',
      400: '#60a5fa',
      500: '#3b82f6',
      600: '#2563eb',
      700: '#1d4ed8',
      800: '#1e40af',
      900: '#1e3a8a',
      950: '#172554',
      DEFAULT: 'rgb(var(--primary))',
      foreground: 'rgb(var(--primary-foreground))',
    },
    success: {
      50: '#f0fdf4',
      100: '#dcfce7',
      200: '#bbf7d0',
      300: '#86efac',
      400: '#4ade80',
      500: '#22c55e',
      600: '#16a34a',
      700: '#15803d',
      DEFAULT: '#22c55e',
    },
    accent: {
      50: '#fffbeb',
      100: '#fef3c7',
      200: '#fde68a',
      300: '#fcd34d',
      400: '#fbbf24',
      500: '#f59e0b',
      600: '#d97706',
      700: '#b45309',
      800: '#92400e',
      900: '#78350f',
      DEFAULT: 'rgb(var(--accent))',
      foreground: 'rgb(var(--accent-foreground))',
    },
    secondary: {
      50: 'var(--secondary-50)',
      100: 'var(--secondary-100)',
      200: 'var(--secondary-200)',
      300: 'var(--secondary-300)',
      400: 'var(--secondary-400)',
      500: 'var(--secondary-500)',
      600: 'var(--secondary-600)',
      700: 'var(--secondary-700)',
      800: 'var(--secondary-800)',
      900: 'var(--secondary-900)',
      950: 'var(--secondary-950)',
      DEFAULT: 'rgb(var(--secondary))',
      foreground: 'rgb(var(--secondary-foreground))',
    },
    gray: {
      50: 'var(--gray-50)',
      100: 'var(--gray-100)',
      200: 'var(--gray-200)',
      300: 'var(--gray-300)',
      400: 'var(--gray-400)',
      500: 'var(--gray-500)',
      600: 'var(--gray-600)',
      700: 'var(--gray-700)',
      800: 'var(--gray-800)',
      900: 'var(--gray-900)',
      950: 'var(--gray-950)',
    },
    warning: {
      50: 'var(--warning-50)',
      500: 'var(--warning-500)',
      600: 'var(--warning-600)',
      700: 'var(--warning-700)',
      DEFAULT: 'var(--warning-500)',
    },
    error: {
      50: 'var(--error-50)',
      500: 'var(--error-500)',
      600: 'var(--error-600)',
      700: 'var(--error-700)',
      DEFAULT: 'var(--error-500)',
    },
    info: {
      50: 'var(--info-50)',
      500: 'var(--info-500)',
      600: 'var(--info-600)',
      700: 'var(--info-700)',
      DEFAULT: 'var(--info-500)',
    },
    danger: {
      50: 'var(--danger-50)',
      500: 'var(--danger-500)',
      600: 'var(--danger-600)',
      700: 'var(--danger-700)',
      DEFAULT: 'var(--danger-500)',
    },
    // Semantic colors
    border: "rgb(var(--border))",
    input: "rgb(var(--input))",
    ring: "rgb(var(--ring))",
    background: "rgb(var(--background))",
    foreground: "rgb(var(--foreground))",
    destructive: {
      DEFAULT: "rgb(var(--destructive))",
      foreground: "rgb(var(--destructive-foreground))",
    },
    muted: {
      DEFAULT: "rgb(var(--muted))",
      foreground: "rgb(var(--muted-foreground))",
    },
    popover: {
      DEFAULT: "rgb(var(--popover))",
      foreground: "rgb(var(--popover-foreground))",
    },
    card: {
      DEFAULT: "rgb(var(--card))",
      foreground: "rgb(var(--card-foreground))",
    },
  },
  typography: {
    fontFamily: {
      sans: ['"Inter"', '"DM Sans"', 'system-ui', '-apple-system', 'sans-serif'],
      serif: ['"Fraunces"', '"Playfair Display"', '"Instrument Serif"', 'serif'],
      mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
    },
    fontSize: {
      xs: ['var(--font-size-xs)', { lineHeight: 'var(--line-height-normal)' }],
      sm: ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
      base: ['var(--font-size-base)', { lineHeight: 'var(--line-height-relaxed)' }],
      lg: ['var(--font-size-lg)', { lineHeight: 'var(--line-height-relaxed)' }],
      xl: ['var(--font-size-xl)', { lineHeight: 'var(--line-height-snug)' }],
      '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-snug)' }],
      '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-snug)' }],
      '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
      '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-tight)' }],
      '6xl': ['var(--font-size-6xl)', { lineHeight: 'var(--line-height-tight)' }],
      '7xl': ['var(--font-size-7xl)', { lineHeight: 'var(--line-height-tight)' }],
    },
    fontWeight: {
      light: 'var(--font-weight-light)',
      normal: 'var(--font-weight-normal)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
      extrabold: 'var(--font-weight-extrabold)',
      black: 'var(--font-weight-black)',
    },
  },
  spacing: {
    0: 'var(--space-0)',
    1: 'var(--space-1)',
    2: 'var(--space-2)',
    3: 'var(--space-3)',
    4: 'var(--space-4)',
    5: 'var(--space-5)',
    6: 'var(--space-6)',
    8: 'var(--space-8)',
    10: 'var(--space-10)',
    12: 'var(--space-12)',
    16: 'var(--space-16)',
    20: 'var(--space-20)',
    24: 'var(--space-24)',
    32: 'var(--space-32)',
  },
  borderRadius: {
    none: 'var(--radius-none)',
    sm: 'var(--radius-sm)',
    base: 'var(--radius-base)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    '3xl': 'var(--radius-3xl)',
    full: 'var(--radius-full)',
  },
  shadows: {
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    base: 'var(--shadow-base)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    '2xl': 'var(--shadow-2xl)',
  },
  zIndex: {
    0: '0',
    10: '10',
    20: '20',
    30: '30',
    40: '40',
    50: '50',
  },
  animation: {
    duration: {
      fast: 'var(--transition-fast)',
      base: 'var(--transition-base)',
      slow: 'var(--transition-slow)',
      smooth: 'var(--transition-smooth)',
    },
    easing: {
      DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      spring: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      elastic: 'cubic-bezier(0.68, -0.6, 0.32, 1.6)',
    }
  }
} as const;

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        ...designSystem.colors,
        // PRIMARY: Professional Blue (main brand color)
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',  // Main blue
          600: '#2563eb',  // Primary action color
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          DEFAULT: '#3b82f6',
          foreground: '#ffffff',
        },

        // SUCCESS/TURTLE: Green (only for success states & turtle elements)
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',  // Turtle green
          600: '#16a34a',
          700: '#15803d',
          DEFAULT: '#22c55e',
          foreground: '#ffffff',
        },

        // ACCENT: Sky Blue / Cyan (replacing Yellow)
        accent: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          DEFAULT: '#0ea5e9',
          foreground: '#ffffff',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', ...designSystem.typography.fontFamily.sans],
        serif: ['var(--font-fraunces)', ...designSystem.typography.fontFamily.serif],
        mono: [...designSystem.typography.fontFamily.mono],
      },
      fontSize: designSystem.typography.fontSize as any,
      fontWeight: designSystem.typography.fontWeight,
      spacing: designSystem.spacing,
      borderRadius: designSystem.borderRadius,
      boxShadow: designSystem.shadows,
      zIndex: designSystem.zIndex,
      transitionDuration: designSystem.animation.duration,
      transitionTimingFunction: designSystem.animation.easing,
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('tailwindcss-animate'),
  ],
}

export default config