export const designSystem = {
  colors: {
    primary: {
      50: '#eff6ff',
      100: '#dbeafe',
      200: '#bfdbfe',
      300: '#93c5fd',
      400: '#60a5fa',
      500: '#3b82f6',
      600: '#2563eb',
      700: '#1d4ed8',
      800: '#1e40af',
      900: '#1e3a8a',
      950: '#172554',
      DEFAULT: 'rgb(var(--primary))',
      foreground: 'rgb(var(--primary-foreground))',
    },
    success: {
      50: '#f0fdf4',
      100: '#dcfce7',
      200: '#bbf7d0',
      300: '#86efac',
      400: '#4ade80',
      500: '#22c55e',
      600: '#16a34a',
      700: '#15803d',
      DEFAULT: '#22c55e',
    },
    accent: {
      50: '#fffbeb',
      100: '#fef3c7',
      200: '#fde68a',
      300: '#fcd34d',
      400: '#fbbf24',
      500: '#f59e0b',
      600: '#d97706',
      700: '#b45309',
      800: '#92400e',
      900: '#78350f',
      DEFAULT: 'rgb(var(--accent))',
      foreground: 'rgb(var(--accent-foreground))',
    },
    secondary: {
      50: 'var(--secondary-50)',
      100: 'var(--secondary-100)',
      200: 'var(--secondary-200)',
      300: 'var(--secondary-300)',
      400: 'var(--secondary-400)',
      500: 'var(--secondary-500)',
      600: 'var(--secondary-600)',
      700: 'var(--secondary-700)',
      800: 'var(--secondary-800)',
      900: 'var(--secondary-900)',
      950: 'var(--secondary-950)',
      DEFAULT: 'rgb(var(--secondary))',
      foreground: 'rgb(var(--secondary-foreground))',
    },
    gray: {
      50: 'var(--gray-50)',
      100: 'var(--gray-100)',
      200: 'var(--gray-200)',
      300: 'var(--gray-300)',
      400: 'var(--gray-400)',
      500: 'var(--gray-500)',
      600: 'var(--gray-600)',
      700: 'var(--gray-700)',
      800: 'var(--gray-800)',
      900: 'var(--gray-900)',
      950: 'var(--gray-950)',
    },
    warning: {
      50: 'var(--warning-50)',
      500: 'var(--warning-500)',
      600: 'var(--warning-600)',
      700: 'var(--warning-700)',
      DEFAULT: 'var(--warning-500)',
    },
    error: {
      50: 'var(--error-50)',
      500: 'var(--error-500)',
      600: 'var(--error-600)',
      700: 'var(--error-700)',
      DEFAULT: 'var(--error-500)',
    },
    info: {
      50: 'var(--info-50)',
      500: 'var(--info-500)',
      600: 'var(--info-600)',
      700: 'var(--info-700)',
      DEFAULT: 'var(--info-500)',
    },
    danger: {
      50: 'var(--danger-50)',
      500: 'var(--danger-500)',
      600: 'var(--danger-600)',
      700: 'var(--danger-700)',
      DEFAULT: 'var(--danger-500)',
    },
    // Semantic colors
    border: "rgb(var(--border))",
    input: "rgb(var(--input))",
    ring: "rgb(var(--ring))",
    background: "rgb(var(--background))",
    foreground: "rgb(var(--foreground))",
    destructive: {
      DEFAULT: "rgb(var(--destructive))",
      foreground: "rgb(var(--destructive-foreground))",
    },
    muted: {
      DEFAULT: "rgb(var(--muted))",
      foreground: "rgb(var(--muted-foreground))",
    },
    popover: {
      DEFAULT: "rgb(var(--popover))",
      foreground: "rgb(var(--popover-foreground))",
    },
    card: {
      DEFAULT: "rgb(var(--card))",
      foreground: "rgb(var(--card-foreground))",
    },
  },
  typography: {
    fontFamily: {
      sans: ['"Inter"', '"DM Sans"', 'system-ui', '-apple-system', 'sans-serif'],
      serif: ['"Fraunces"', '"Playfair Display"', '"Instrument Serif"', 'serif'],
      mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
    },
    fontSize: {
      xs: ['var(--font-size-xs)', { lineHeight: 'var(--line-height-normal)' }],
      sm: ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
      base: ['var(--font-size-base)', { lineHeight: 'var(--line-height-relaxed)' }],
      lg: ['var(--font-size-lg)', { lineHeight: 'var(--line-height-relaxed)' }],
      xl: ['var(--font-size-xl)', { lineHeight: 'var(--line-height-snug)' }],
      '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-snug)' }],
      '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-snug)' }],
      '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
      '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-tight)' }],
      '6xl': ['var(--font-size-6xl)', { lineHeight: 'var(--line-height-tight)' }],
      '7xl': ['var(--font-size-7xl)', { lineHeight: 'var(--line-height-tight)' }],
    },
    fontWeight: {
      light: 'var(--font-weight-light)',
      normal: 'var(--font-weight-normal)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
      extrabold: 'var(--font-weight-extrabold)',
      black: 'var(--font-weight-black)',
    },
  },
  spacing: {
    0: 'var(--space-0)',
    1: 'var(--space-1)',
    2: 'var(--space-2)',
    3: 'var(--space-3)',
    4: 'var(--space-4)',
    5: 'var(--space-5)',
    6: 'var(--space-6)',
    8: 'var(--space-8)',
    10: 'var(--space-10)',
    12: 'var(--space-12)',
    16: 'var(--space-16)',
    20: 'var(--space-20)',
    24: 'var(--space-24)',
    32: 'var(--space-32)',
  },
  borderRadius: {
    none: 'var(--radius-none)',
    sm: 'var(--radius-sm)',
    base: 'var(--radius-base)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    '3xl': 'var(--radius-3xl)',
    full: 'var(--radius-full)',
  },
  shadows: {
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    base: 'var(--shadow-base)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    '2xl': 'var(--shadow-2xl)',
  },
  zIndex: {
    0: '0',
    10: '10',
    20: '20',
    30: '30',
    40: '40',
    50: '50',
  },
  animation: {
    duration: {
      fast: 'var(--transition-fast)',
      base: 'var(--transition-base)',
      slow: 'var(--transition-slow)',
      smooth: 'var(--transition-smooth)',
    },
    easing: {
      DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      spring: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      elastic: 'cubic-bezier(0.68, -0.6, 0.32, 1.6)',
    }
  }
} as const;

export const componentStyles = {
  button: {
    base: "inline-flex items-center justify-center whitespace-nowrap rounded-lg text-sm font-medium ring-offset-background transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 button-press",
    variants: {
      primary: "bg-primary-600 text-white hover:bg-primary-700 hover:shadow-md hover:-translate-y-0.5 active:translate-y-0 shadow-sm",
      secondary: "bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 border border-gray-300 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700 hover:shadow active:translate-y-0",
      ghost: "bg-transparent text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors duration-200",
      danger: "bg-error-500 text-white hover:bg-error-600 hover:shadow-lg hover:-translate-y-0.5",
      success: "bg-success-600 text-white hover:bg-success-700 hover:shadow-lg hover:-translate-y-0.5",
      outline: "border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 hover:bg-gray-50 dark:hover:bg-gray-800 hover:border-gray-300 dark:hover:border-gray-700",
      destructive: "bg-error-500 text-white hover:bg-error-600 hover:shadow-lg hover:-translate-y-0.5",
      default: "bg-primary-600 text-white hover:bg-primary-700 hover:shadow-md hover:-translate-y-0.5 active:translate-y-0 shadow-sm",
      link: "text-primary-600 underline-offset-4 hover:underline",
    },
    sizes: {
      sm: "h-9 rounded-lg px-4 text-sm",
      md: "h-10 px-6 py-3 rounded-xl text-sm",
      lg: "h-12 rounded-xl px-8 text-base",
      xl: "h-14 rounded-2xl px-10 text-lg",
      default: "h-10 px-6 py-3 rounded-xl text-sm",
      icon: "h-10 w-10 rounded-lg",
    },
  },
  card: {
    base: "bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 shadow-sm transition-all duration-300 card-hover",
    rounded: "rounded-xl",
    padding: {
      sm: "p-4",
      md: "p-6",
      lg: "p-8",
    },
    hover: "hover:shadow-lg hover:border-gray-300 dark:hover:border-gray-700 hover:-translate-y-1",
  },
  input: {
    base: "flex w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 px-4 py-2.5 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-gray-400 text-gray-900 dark:text-gray-100 transition-colors duration-200",
    focus: "focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:border-transparent",
    error: "border-error-500 focus:ring-error-500 focus-visible:ring-error-500",
    disabled: "disabled:cursor-not-allowed disabled:bg-gray-100 dark:disabled:bg-gray-900 disabled:opacity-50",
  },
  badge: {
    base: "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
    variants: {
      success: "border-transparent bg-success-50 text-success-700 dark:bg-success-900/30 dark:text-success-400",
      error: "border-transparent bg-error-50 text-error-700 dark:bg-error-900/30 dark:text-error-400",
      warning: "border-transparent bg-warning-50 text-warning-700 dark:bg-warning-900/30 dark:text-warning-400",
      info: "border-transparent bg-info-50 text-info-700 dark:bg-info-900/30 dark:text-info-400",
      neutral: "border-transparent bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300",
      accent: "border-transparent bg-primary-50 text-primary-700 dark:bg-primary-900/30 dark:text-primary-400",
      outline: "text-foreground",
      secondary: "border-transparent bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300",
      destructive: "border-transparent bg-error-50 text-error-700 dark:bg-error-900/30 dark:text-error-400",
      default: "border-transparent bg-primary-50 text-primary-700 dark:bg-primary-900/30 dark:text-primary-400",
    },
  },
  documentCard: {
    container: "group relative flex flex-col overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-gray-300 hover:shadow-lg dark:border-gray-800 dark:bg-gray-900 dark:hover:border-gray-700 cursor-pointer card-hover",
    thumbnail: "relative aspect-[16/10] w-full overflow-hidden bg-gray-100 dark:bg-gray-800",
    thumbnailImage: "h-full w-full object-cover transition-transform duration-500 group-hover:scale-110",
    content: "flex flex-1 flex-col p-4",
    title: "text-heading-sm line-clamp-1 font-serif font-semibold text-gray-900 transition-colors duration-200 group-hover:text-primary-600 dark:text-gray-100 dark:group-hover:text-primary-400",
    meta: "mt-2 flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400",
  },
  chatBubble: {
    user: "relative rounded-2xl rounded-tr-md bg-primary-600 px-4 py-3 text-white shadow-sm animate-in slide-in-from-right-2 duration-300",
    assistant: "relative rounded-2xl rounded-tl-md bg-gray-100 dark:bg-gray-800 px-4 py-3 text-gray-900 dark:text-gray-100 shadow-sm animate-in slide-in-from-left-2 duration-300",
  },
  skeleton: {
    base: "animate-pulse rounded bg-gray-200 dark:bg-gray-800",
  },
}