export const designSystem = {
  colors: {
    primary: {
      50: 'var(--primary-50)',
      100: 'var(--primary-100)',
      200: 'var(--primary-200)',
      300: 'var(--primary-300)',
      400: 'var(--primary-400)',
      500: 'var(--primary-500)',
      600: 'var(--primary-600)',
      700: 'var(--primary-700)',
      800: 'var(--primary-800)',
      900: 'var(--primary-900)',
      DEFAULT: 'rgb(var(--primary))',
      foreground: 'rgb(var(--primary-foreground))',
    },
    secondary: {
      50: 'var(--secondary-50)',
      100: 'var(--secondary-100)',
      200: 'var(--secondary-200)',
      300: 'var(--secondary-300)',
      400: 'var(--secondary-400)',
      500: 'var(--secondary-500)',
      600: 'var(--secondary-600)',
      700: 'var(--secondary-700)',
      800: 'var(--secondary-800)',
      900: 'var(--secondary-900)',
      DEFAULT: 'rgb(var(--secondary))',
      foreground: 'rgb(var(--secondary-foreground))',
    },
    accent: {
      50: 'var(--accent-50)',
      100: 'var(--accent-100)',
      200: 'var(--accent-200)',
      300: 'var(--accent-300)',
      400: 'var(--accent-400)',
      500: 'var(--accent-500)',
      600: 'var(--accent-600)',
      700: 'var(--accent-700)',
      800: 'var(--accent-800)',
      900: 'var(--accent-900)',
      DEFAULT: 'rgb(var(--accent))',
      foreground: 'rgb(var(--accent-foreground))',
    },
    gray: {
      50: 'var(--gray-50)',
      100: 'var(--gray-100)',
      200: 'var(--gray-200)',
      300: 'var(--gray-300)',
      400: 'var(--gray-400)',
      500: 'var(--gray-500)',
      600: 'var(--gray-600)',
      700: 'var(--gray-700)',
      800: 'var(--gray-800)',
      900: 'var(--gray-900)',
    },
    success: {
      50: 'var(--success-50)',
      500: 'var(--success-500)',
      600: 'var(--success-600)',
      700: 'var(--success-700)',
      DEFAULT: 'var(--success-500)',
    },
    warning: {
      50: 'var(--warning-50)',
      500: 'var(--warning-500)',
      600: 'var(--warning-600)',
      700: 'var(--warning-700)',
      DEFAULT: 'var(--warning-500)',
    },
    error: {
      50: 'var(--error-50)',
      500: 'var(--error-500)',
      600: 'var(--error-600)',
      700: 'var(--error-700)',
      DEFAULT: 'var(--error-500)',
    },
    info: {
      50: 'var(--info-50)',
      500: 'var(--info-500)',
      600: 'var(--info-600)',
      700: 'var(--info-700)',
      DEFAULT: 'var(--info-500)',
    },
    danger: {
      50: 'var(--danger-50)',
      500: 'var(--danger-500)',
      600: 'var(--danger-600)',
      700: 'var(--danger-700)',
      DEFAULT: 'var(--danger-500)',
    },
    // Semantic colors
    border: "rgb(var(--border))",
    input: "rgb(var(--input))",
    ring: "rgb(var(--ring))",
    background: "rgb(var(--background))",
    foreground: "rgb(var(--foreground))",
    destructive: {
      DEFAULT: "rgb(var(--destructive))",
      foreground: "rgb(var(--destructive-foreground))",
    },
    muted: {
      DEFAULT: "rgb(var(--muted))",
      foreground: "rgb(var(--muted-foreground))",
    },
    popover: {
      DEFAULT: "rgb(var(--popover))",
      foreground: "rgb(var(--popover-foreground))",
    },
    card: {
      DEFAULT: "rgb(var(--card))",
      foreground: "rgb(var(--card-foreground))",
    },
  },
  typography: {
    fontFamily: {
      sans: ['"Inter"', '"DM Sans"', 'system-ui', '-apple-system', 'sans-serif'],
      serif: ['"Fraunces"', '"Playfair Display"', '"Instrument Serif"', 'serif'],
      mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
    },
    fontSize: {
      xs: ['var(--font-size-xs)', { lineHeight: 'var(--line-height-normal)' }],
      sm: ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
      base: ['var(--font-size-base)', { lineHeight: 'var(--line-height-relaxed)' }],
      lg: ['var(--font-size-lg)', { lineHeight: 'var(--line-height-relaxed)' }],
      xl: ['var(--font-size-xl)', { lineHeight: 'var(--line-height-snug)' }],
      '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-snug)' }],
      '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-snug)' }],
      '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
      '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-tight)' }],
      '6xl': ['var(--font-size-6xl)', { lineHeight: 'var(--line-height-tight)' }],
      '7xl': ['var(--font-size-7xl)', { lineHeight: 'var(--line-height-tight)' }],
    },
    fontWeight: {
      light: 'var(--font-weight-light)',
      normal: 'var(--font-weight-normal)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
      extrabold: 'var(--font-weight-extrabold)',
      black: 'var(--font-weight-black)',
    },
  },
  spacing: {
    0: 'var(--space-0)',
    1: 'var(--space-1)',
    2: 'var(--space-2)',
    3: 'var(--space-3)',
    4: 'var(--space-4)',
    5: 'var(--space-5)',
    6: 'var(--space-6)',
    8: 'var(--space-8)',
    10: 'var(--space-10)',
    12: 'var(--space-12)',
    16: 'var(--space-16)',
    20: 'var(--space-20)',
    24: 'var(--space-24)',
    32: 'var(--space-32)',
  },
  borderRadius: {
    none: 'var(--radius-none)',
    sm: 'var(--radius-sm)',
    base: 'var(--radius-base)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    '3xl': 'var(--radius-3xl)',
    full: 'var(--radius-full)',
  },
  shadows: {
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    base: 'var(--shadow-base)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    '2xl': 'var(--shadow-2xl)',
  },
  zIndex: {
    0: '0',
    10: '10',
    20: '20',
    30: '30',
    40: '40',
    50: '50',
  },
  animation: {
    duration: {
      fast: 'var(--transition-fast)',
      base: 'var(--transition-base)',
      slow: 'var(--transition-slow)',
      smooth: 'var(--transition-smooth)',
    },
    easing: {
      DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      spring: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      elastic: 'cubic-bezier(0.68, -0.6, 0.32, 1.6)',
    }
  }
} as const;

export const componentStyles = {
  button: {
    base: "inline-flex items-center justify-center whitespace-nowrap rounded-lg text-sm font-medium ring-offset-background transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
    variants: {
      primary: "bg-primary-600 text-white hover:bg-primary-700 hover:shadow-lg hover:-translate-y-0.5 active:translate-y-0",
      secondary: "bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-700",
      ghost: "bg-transparent text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800",
      danger: "bg-error-500 text-white hover:bg-error-600 hover:shadow-lg hover:-translate-y-0.5",
      success: "bg-success-600 text-white hover:bg-success-700 hover:shadow-lg hover:-translate-y-0.5",
      outline: "border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 hover:bg-gray-50 dark:hover:bg-gray-800 hover:border-gray-300 dark:hover:border-gray-700",
      destructive: "bg-error-500 text-white hover:bg-error-600 hover:shadow-lg hover:-translate-y-0.5",
      default: "bg-primary-600 text-white hover:bg-primary-700 hover:shadow-lg hover:-translate-y-0.5 active:translate-y-0",
      link: "text-primary-600 underline-offset-4 hover:underline",
    },
    sizes: {
      sm: "h-9 rounded-lg px-4",
      md: "h-10 px-6 py-3",
      lg: "h-12 rounded-xl px-8 text-base",
      xl: "h-14 rounded-2xl px-10 text-lg",
      default: "h-10 px-6 py-3",
      icon: "h-10 w-10",
    },
  },
  card: {
    base: "bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 shadow-sm transition-all duration-200",
    rounded: "rounded-xl",
    padding: {
      sm: "p-4",
      md: "p-6",
      lg: "p-8",
    },
    hover: "hover:shadow-lg hover:-translate-y-1 hover:border-primary-200 dark:hover:border-primary-800",
  },
  input: {
    base: "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground transition-all duration-200",
    focus: "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
    error: "border-error-500 focus-visible:ring-error-500",
    disabled: "disabled:cursor-not-allowed disabled:opacity-50",
  },
}

